---
- name: Create HomeCam data directories
  ansible.builtin.file:
    path: "{{ platform_data_root }}/{{ item }}"
    state: directory
    owner: "999"
    group: "999"
    mode: "0755"
  loop:
    - mongodb
    - mongodb/data
    - mongodb/config
