# Home Platform — Initial Stack Setup
# Single source of truth: root .env (auto-generated by 'make preflight')
# Usage:  make up              → full stack in dependency order
#         make preflight       → verify tools + generate .env secrets
#         make show-credentials → print all access URLs and passwords

.DEFAULT_GOAL := help
.ONESHELL:
SHELL       := /bin/bash

.PHONY: help preflight submodules envs \
        up down destroy show-credentials \
        traefik traefik-down \
        authentik authentik-down authentik-setup \
        awx awx-down awx-configure \
        aistack aistack-down \
        homecam homecam-down \
        sentinel-home sentinel-home-down \
        status

REPO := $(shell pwd)

# AWX-as-code overrides — pass on CLI: make awx-configure AWX_PASSWORD=secret
AWX_HOST     ?= http://localhost:8052
AWX_USER     ?= admin
AWX_PASSWORD ?=

# Escape-free colour vars (used with echo -e or printf)
CC  := \033[36m
CG  := \033[32m
CY  := \033[33m
CR  := \033[31m
CB  := \033[1m
CX  := \033[0m

# ─── Help ─────────────────────────────────────────────────────────────────────

##@ Help

help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "\n$(CB)Home Platform$(CX)\n\n$(CB)Usage:$(CX)\n  make $(CC)<target>$(CX)\n"} \
	  /^[a-zA-Z_-]+:.*?##/ { printf "  $(CC)%-26s$(CX) %s\n", $$1, $$2 } \
	  /^##@/ { printf "\n$(CB)%s$(CX)\n", substr($$0, 5) }' $(MAKEFILE_LIST)
	@echo ""

# ─── Prerequisites & secrets ──────────────────────────────────────────────────

##@ Prerequisites

preflight: ## Verify tools + create/validate root .env (auto-generates missing secrets)
	@set -euo pipefail
	echo -e "$(CB)Checking prerequisites...$(CX)"
	missing=0
	for tool in docker git curl openssl python3; do
	    command -v "$$tool" >/dev/null 2>&1 \
	        && printf "  $(CG)✔$(CX)  %-18s found\n" "$$tool" \
	        || { printf "  $(CR)✘$(CX)  %-18s MISSING\n" "$$tool"; missing=1; }
	done
	docker compose version >/dev/null 2>&1 \
	    && printf "  $(CG)✔$(CX)  %-18s found\n" "docker compose" \
	    || { printf "  $(CR)✘$(CX)  %-18s MISSING\n" "docker compose"; missing=1; }
	for tool in k3d kubectl; do
	    command -v "$$tool" >/dev/null 2>&1 \
	        && printf "  $(CG)✔$(CX)  %-18s found\n" "$$tool" \
	        || { printf "  $(CR)✘$(CX)  %-18s MISSING\n" "$$tool"; missing=1; }
	done
	command -v ansible-playbook >/dev/null 2>&1 \
	    && printf "  $(CG)✔$(CX)  %-18s found\n" "ansible-playbook" \
	    || printf "  $(CY)!$(CX)  %-18s optional (needed for awx-configure)\n" "ansible-playbook"
	[ "$$missing" -eq 0 ] || { echo -e "\n$(CR)Install missing tools then retry.$(CX)"; exit 1; }
	echo ""
	echo -e "$(CB)Generating root .env...$(CX)"
	[ -f "$(REPO)/.env" ] || touch "$(REPO)/.env"
	# Idempotent setter: adds var if absent, fills it in if empty, leaves it alone if set
	_s() {
	    local var="$$1" val="$$2"
	    if ! grep -q "^$$var=" "$(REPO)/.env" 2>/dev/null; then
	        printf '%s=%s\n' "$$var" "$$val" >> "$(REPO)/.env"
	        printf "  $(CG)ADD$(CX)  %s\n" "$$var"
	    elif grep -q "^$$var=$$" "$(REPO)/.env" 2>/dev/null; then
	        sed -i "s|^$$var=$$|$$var=$$val|" "$(REPO)/.env"
	        printf "  $(CG)SET$(CX)  %s\n" "$$var"
	    fi
	}
	h64() { openssl rand -hex 32; }           # 64 hex chars
	h32() { openssl rand -hex 16; }           # 32 hex chars
	h40() { openssl rand -hex 20; }           # 40 hex chars
	p24() { openssl rand -base64 18 | tr -d '\n/+='; }  # 24 alnum chars
	# ── Platform
	_s DOMAIN                           blackiechan.net
	_s BIND_ADDRESS                     192.168.1.100
	_s TZ                               America/New_York
	# ── Authentik
	_s AUTHENTIK_VERSION                2026.2
	_s AUTHENTIK_SECRET_KEY             "$$(h64)"
	_s AUTHENTIK_PG_PASSWORD            "$$(h32)"
	_s AUTHENTIK_BOOTSTRAP_PASSWORD     "$$(p24)"
	_s AUTHENTIK_BOOTSTRAP_TOKEN        "$$(h40)"
	# ── blackie-chan (platform admin user)
	_s BLACKIE_CHAN_PASSWORD             "$$(p24)"
	# ── AWX
	_s AWX_VERSION                      24.6.0
	_s AWX_HOST_PORT                    8052
	_s AWX_ADMIN_USER                   admin
	_s AWX_ADMIN_PASSWORD               "$$(p24)"
	_s AWX_SECRET_KEY                   "$$(h64)"
	_s AWX_PG_DATABASE                  awx
	_s AWX_PG_USERNAME                  awx
	_s AWX_PG_PASSWORD                  "$$(h32)"
	_s AWX_REDIS_PASSWORD               "$$(h32)"
	# ── AI Platform (local-aistack)
	_s AISTACK_POSTGRES_PASSWORD        "$$(h32)"
	_s AISTACK_QDRANT_API_KEY           "$$(h32)"
	_s AISTACK_OPENWEBUI_SECRET_KEY     "$$(h32)"
	_s AISTACK_JUPYTER_TOKEN            "$$(h32)"
	_s AISTACK_MINIO_ROOT_PASSWORD      "$$(p24)"
	_s AISTACK_PORTAINER_ADMIN_PASSWORD "$$(p24)"
	_s AISTACK_AP_ENCRYPTION_KEY        "$$(h32)"
	_s AISTACK_AP_JWT_SECRET            "$$(h64)"
	_s AISTACK_LITELLM_MASTER_KEY       "sk-$$(h32)"
	_s AISTACK_LANGFUSE_PUBLIC_KEY      "pk-lf-$$(h32)"
	_s AISTACK_LANGFUSE_SECRET_KEY      "sk-lf-$$(h32)"
	_s AISTACK_LANGFUSE_NEXTAUTH_SECRET "$$(h32)"
	_s AISTACK_LANGFUSE_SALT            "$$(h32)"
	_s AISTACK_LANGFUSE_ENCRYPTION_KEY  "$$(h64)"
	_s AISTACK_API_JWT_SECRET           "$$(h32)"
	# ── Git / Docker registry (fill in manually when needed)
	_s GIT_REPO_URL                     git@github.com:fntundi/Local-Stuff.git
	_s GIT_USER                         ""
	_s GIT_TOKEN                        ""
	_s DOCKER_USER                      ""
	_s DOCKER_PASSWORD                  ""
	echo ""
	echo -e "$(CG)root .env ready.$(CX)  Set GIT_USER, GIT_TOKEN, DOCKER_USER/PASSWORD when needed."

submodules: ## Initialise and update all git submodules
	@echo -e "$(CC)Updating submodules...$(CX)"
	git submodule update --init --recursive
	echo "  Done."

envs: ## Generate local-aistack .env.prod from root .env secrets
	@set -euo pipefail
	[ -f "$(REPO)/.env" ] || { echo -e "$(CR)Run 'make preflight' first$(CX)"; exit 1; }
	set -a; . "$(REPO)/.env"; set +a
	if [ ! -d local-aistack ]; then
	    echo -e "  $(CY)SKIP$(CX)  local-aistack/ not found — run 'make submodules' first"
	    exit 0
	fi
	src="local-aistack/env/.env.prod.example"
	dst="local-aistack/env/.env.prod"
	if [ -f "$$dst" ] && ! grep -q "change_me" "$$dst" 2>/dev/null; then
	    echo -e "  $(CY)SKIP$(CX)  $$dst already configured"
	    exit 0
	fi
	[ -f "$$src" ] || { echo -e "  $(CR)ERROR$(CX)  $$src not found"; exit 1; }
	pg="$$AISTACK_POSTGRES_PASSWORD"
	cp "$$src" "$$dst"
	# Substitute each secret — values are hex/alphanumeric so | is safe as separator
	sed -i "s|^BIND_ADDRESS=.*|BIND_ADDRESS=$$BIND_ADDRESS|"                                               "$$dst"
	sed -i "s|^POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=$$pg|"                                               "$$dst"
	sed -i "s|^DATABASE_URL=.*|DATABASE_URL=postgresql://activepieces_user:$$pg@postgres:5432/activepieces_db|" "$$dst"
	sed -i "s|^MLFLOW_BACKEND_STORE_URI=.*|MLFLOW_BACKEND_STORE_URI=postgresql://activepieces_user:$$pg@postgres:5432/activepieces_db|" "$$dst"
	sed -i "s|^LITELLM_DATABASE_URL=.*|LITELLM_DATABASE_URL=postgresql://activepieces_user:$$pg@postgres:5432/litellm_db|"             "$$dst"
	sed -i "s|^LANGFUSE_DATABASE_URL=.*|LANGFUSE_DATABASE_URL=postgresql://activepieces_user:$$pg@postgres:5432/langfuse_db|"          "$$dst"
	sed -i "s|^QDRANT_API_KEY=.*|QDRANT_API_KEY=$$AISTACK_QDRANT_API_KEY|"                                 "$$dst"
	sed -i "s|^AP_ENCRYPTION_KEY=.*|AP_ENCRYPTION_KEY=$$AISTACK_AP_ENCRYPTION_KEY|"                        "$$dst"
	sed -i "s|^AP_JWT_SECRET=.*|AP_JWT_SECRET=$$AISTACK_AP_JWT_SECRET|"                                    "$$dst"
	sed -i "s|^OPENWEBUI_SECRET_KEY=.*|OPENWEBUI_SECRET_KEY=$$AISTACK_OPENWEBUI_SECRET_KEY|"               "$$dst"
	sed -i "s|^JUPYTER_TOKEN=.*|JUPYTER_TOKEN=$$AISTACK_JUPYTER_TOKEN|"                                    "$$dst"
	sed -i "s|^MINIO_ROOT_PASSWORD=.*|MINIO_ROOT_PASSWORD=$$AISTACK_MINIO_ROOT_PASSWORD|"                  "$$dst"
	sed -i "s|^PORTAINER_ADMIN_PASSWORD=.*|PORTAINER_ADMIN_PASSWORD=$$AISTACK_PORTAINER_ADMIN_PASSWORD|"   "$$dst"
	sed -i "s|^LITELLM_MASTER_KEY=.*|LITELLM_MASTER_KEY=$$AISTACK_LITELLM_MASTER_KEY|"                    "$$dst"
	sed -i "s|^LANGFUSE_PUBLIC_KEY=.*|LANGFUSE_PUBLIC_KEY=$$AISTACK_LANGFUSE_PUBLIC_KEY|"                  "$$dst"
	sed -i "s|^LANGFUSE_SECRET_KEY=.*|LANGFUSE_SECRET_KEY=$$AISTACK_LANGFUSE_SECRET_KEY|"                  "$$dst"
	sed -i "s|^LANGFUSE_NEXTAUTH_SECRET=.*|LANGFUSE_NEXTAUTH_SECRET=$$AISTACK_LANGFUSE_NEXTAUTH_SECRET|"   "$$dst"
	sed -i "s|^LANGFUSE_SALT=.*|LANGFUSE_SALT=$$AISTACK_LANGFUSE_SALT|"                                   "$$dst"
	sed -i "s|^LANGFUSE_ENCRYPTION_KEY=.*|LANGFUSE_ENCRYPTION_KEY=$$AISTACK_LANGFUSE_ENCRYPTION_KEY|"      "$$dst"
	sed -i "s|^API_JWT_SECRET=.*|API_JWT_SECRET=$$AISTACK_API_JWT_SECRET|"                                 "$$dst"
	echo -e "  $(CG)GEN$(CX)   $$dst"

# ─── Full stack ───────────────────────────────────────────────────────────────

##@ Full Stack

up: preflight submodules envs traefik authentik authentik-setup awx aistack homecam sentinel-home show-credentials ## Deploy the full stack in dependency order

down: traefik-down authentik-down awx-down aistack-down homecam-down sentinel-home-down ## Stop all services (data volumes preserved)
	@echo "All services stopped."

destroy: ## Tear down everything — removes containers, volumes, and k3d clusters
	@echo -e "$(CB)$(CR)Destroying all services and data...$(CX)"
	-docker compose --project-name traefik-gw -f traefik/docker-compose.yml   down -v 2>/dev/null || true
	-docker compose --project-name authentik   -f authentik/docker-compose.yml down -v 2>/dev/null || true
	-docker compose --project-name awx         -f awx/docker-compose.yml       down -v 2>/dev/null || true
	-$(MAKE) -C local-aistack down 2>/dev/null || true
	-k3d cluster delete sentinel-noc  2>/dev/null || true
	-k3d cluster delete sentinel-home 2>/dev/null || true
	echo "Destroy complete."

show-credentials: ## Print all service URLs and credentials from root .env
	@set -a; . "$(REPO)/.env"; set +a
	echo ""
	echo -e "$(CB)══════════════════════════════════════════════════════════════$(CX)"
	echo -e "$(CB)  Home Platform — Access & Credentials$(CX)"
	echo -e "$(CB)══════════════════════════════════════════════════════════════$(CX)"
	echo ""
	echo -e "$(CB)  PLATFORM ADMIN$(CX)"
	echo    "  ─────────────────────────────────────────────────────────"
	echo    "  Authentik SSO  : https://authentik.$$DOMAIN"
	echo    "  Username       : blackie-chan"
	printf  "  Password       : $(CG)%s$(CX)\n" "$$BLACKIE_CHAN_PASSWORD"
	echo    "  akadmin pw     : $$AUTHENTIK_BOOTSTRAP_PASSWORD  (Authentik built-in admin)"
	echo ""
	echo -e "$(CB)  AWX$(CX)"
	echo    "  ─────────────────────────────────────────────────────────"
	echo    "  URL            : https://autoans.$$DOMAIN"
	echo    "  Username       : $$AWX_ADMIN_USER"
	printf  "  Password       : $(CG)%s$(CX)\n" "$$AWX_ADMIN_PASSWORD"
	echo ""
	echo -e "$(CB)  AI PLATFORM$(CX)"
	echo    "  ─────────────────────────────────────────────────────────"
	echo    "  OpenWebUI      : https://chat.$$DOMAIN"
	echo    "  JupyterLab     : https://lab.$$DOMAIN          token: $$AISTACK_JUPYTER_TOKEN"
	echo    "  MinIO console  : https://minio.$$DOMAIN        minioadmin / $$AISTACK_MINIO_ROOT_PASSWORD"
	echo    "  Portainer      : https://portainer.$$DOMAIN    admin / $$AISTACK_PORTAINER_ADMIN_PASSWORD"
	echo    "  MLflow         : https://mlflow.$$DOMAIN"
	echo    "  Langfuse       : https://langfuse.$$DOMAIN"
	echo    "  LiteLLM        : https://litellm.$$DOMAIN"
	echo ""
	echo -e "$(CB)  HomeCam$(CX)"
	echo    "  ─────────────────────────────────────────────────────────"
	echo    "  URL            : https://homecam.$$DOMAIN"
	echo    "  NodePort (dev) : http://<host>:30080"
	echo ""
	echo -e "$(CB)  Sentinel-Home$(CX)"
	echo    "  ─────────────────────────────────────────────────────────"
	echo    "  URL            : https://sentinel.$$DOMAIN"
	echo    "  NodePort (dev) : http://<host>:31000"
	echo ""
	echo -e "$(CB)  CI / DevSecOps$(CX)"
	echo    "  ─────────────────────────────────────────────────────────"
	echo    "  Jenkins        : https://leeeroyy.$$DOMAIN   (Authentik OIDC)"
	echo    "  SonarQube      : https://sonarqube.$$DOMAIN  (Authentik SAML)"
	echo    "  GitLab CE      : https://gitlab.$$DOMAIN     (Authentik OIDC)"
	echo ""
	echo    "  Credentials file : $(REPO)/.env"
	echo    "  Run 'make show-credentials' at any time to display this screen."
	echo -e "$(CB)══════════════════════════════════════════════════════════════$(CX)"
	echo ""

# ─── Authentik setup ──────────────────────────────────────────────────────────

##@ Services — Docker Compose (home-server)

authentik-setup: ## Create blackie-chan platform admin + all service groups in Authentik
	@set -euo pipefail
	set -a; . "$(REPO)/.env"; set +a
	AURL="http://localhost:9000"
	echo -e "$(CC)▶  Authentik — user and group provisioning$(CX)"
	echo -n "  Waiting for Authentik API..."
	for i in $$(seq 1 40); do
	    curl -sf --max-time 3 "$$AURL/api/v3/core/users/" \
	        -H "Authorization: Bearer $$AUTHENTIK_BOOTSTRAP_TOKEN" -o /dev/null 2>/dev/null \
	        && { echo " ready"; break; }
	    [ $$i -eq 40 ] && { echo " timeout"; exit 1; }
	    sleep 3
	done
	# Create blackie-chan — on 400 (already exists) fall back to a search
	USER_PK=$$(curl -s -X POST "$$AURL/api/v3/core/users/" \
	    -H "Authorization: Bearer $$AUTHENTIK_BOOTSTRAP_TOKEN" \
	    -H "Content-Type: application/json" \
	    -d '{"username":"blackie-chan","name":"Blackie Chan","is_active":true,"is_superuser":true,"email":"blackie-chan@blackiechan.net","type":"internal"}' \
	    | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('pk',''))" 2>/dev/null || true)
	if [ -z "$$USER_PK" ]; then
	    USER_PK=$$(curl -s "$$AURL/api/v3/core/users/?username=blackie-chan" \
	        -H "Authorization: Bearer $$AUTHENTIK_BOOTSTRAP_TOKEN" \
	        | python3 -c "import sys,json; d=json.load(sys.stdin); r=d.get('results',[]); print(r[0]['pk'] if r else '')" 2>/dev/null)
	fi
	[ -n "$$USER_PK" ] || { echo -e "  $(CR)ERROR$(CX)  Could not create or locate blackie-chan"; exit 1; }
	echo -e "  $(CG)OK$(CX)    blackie-chan created (pk=$$USER_PK)"
	# Set password
	curl -sf -X POST "$$AURL/api/v3/core/users/$$USER_PK/set_password/" \
	    -H "Authorization: Bearer $$AUTHENTIK_BOOTSTRAP_TOKEN" \
	    -H "Content-Type: application/json" \
	    -d "{\"password\":\"$$BLACKIE_CHAN_PASSWORD\"}" -o /dev/null
	echo -e "  $(CG)OK$(CX)    password set"
	# Create each service group and add blackie-chan
	for group in jenkins-admins jenkins-users gitlab-users sonarqube-users homecam-users aistack-users; do
	    GROUP_PK=$$(curl -s -X POST "$$AURL/api/v3/core/groups/" \
	        -H "Authorization: Bearer $$AUTHENTIK_BOOTSTRAP_TOKEN" \
	        -H "Content-Type: application/json" \
	        -d "{\"name\":\"$$group\"}" \
	        | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('pk',''))" 2>/dev/null || true)
	    if [ -z "$$GROUP_PK" ]; then
	        GROUP_PK=$$(curl -s "$$AURL/api/v3/core/groups/?name=$$group" \
	            -H "Authorization: Bearer $$AUTHENTIK_BOOTSTRAP_TOKEN" \
	            | python3 -c "import sys,json; d=json.load(sys.stdin); r=d.get('results',[]); print(r[0]['pk'] if r else '')" 2>/dev/null)
	    fi
	    if [ -n "$$GROUP_PK" ]; then
	        curl -sf -X POST "$$AURL/api/v3/core/groups/$$GROUP_PK/add_user/" \
	            -H "Authorization: Bearer $$AUTHENTIK_BOOTSTRAP_TOKEN" \
	            -H "Content-Type: application/json" \
	            -d "{\"pk\":$$USER_PK}" -o /dev/null
	        echo -e "  $(CG)OK$(CX)    group $$group — blackie-chan added"
	    else
	        echo -e "  $(CY)WARN$(CX)  group $$group — could not create or locate"
	    fi
	done

traefik: ## Deploy Traefik (creates home-net 172.20.0.0/16, TLS termination)
	@set -euo pipefail
	echo -e "$(CC)▶  Traefik$(CX)"
	docker compose --project-name traefik-gw -f traefik/docker-compose.yml up -d
	echo -n "  Waiting for Traefik..."
	for i in $$(seq 1 30); do
	    curl -s --connect-timeout 2 http://localhost:80 -o /dev/null 2>/dev/null && { echo " ready"; break; }
	    [ $$i -eq 30 ] && { echo ""; echo -e "  $(CR)Timeout$(CX) — check: docker compose -p traefik-gw logs"; exit 1; }
	    sleep 2
	done

traefik-down: ## Stop Traefik
	@docker compose --project-name traefik-gw -f traefik/docker-compose.yml down 2>/dev/null || true

authentik: ## Deploy Authentik SSO (requires home-net from Traefik)
	@set -euo pipefail
	echo -e "$(CC)▶  Authentik$(CX)"
	[ -f "$(REPO)/.env" ] || { echo -e "  $(CR)ERROR$(CX)  .env missing — run 'make preflight'"; exit 1; }
	docker compose --project-name authentik -f authentik/docker-compose.yml up -d
	echo -n "  Waiting for Authentik health (~60 s)..."
	for i in $$(seq 1 60); do
	    curl -sf --connect-timeout 2 http://localhost:9000/-/health/live/ -o /dev/null 2>/dev/null && { echo " ready"; break; }
	    [ $$i -eq 60 ] && { echo ""; echo -e "  $(CR)Timeout$(CX) — check: docker compose -p authentik logs"; exit 1; }
	    sleep 3
	done

authentik-down: ## Stop Authentik
	@docker compose --project-name authentik -f authentik/docker-compose.yml down 2>/dev/null || true

awx: ## Deploy AWX automation controller (~2 min startup)
	@set -euo pipefail
	echo -e "$(CC)▶  AWX$(CX)"
	[ -f "$(REPO)/.env" ] || { echo -e "  $(CR)ERROR$(CX)  .env missing — run 'make preflight'"; exit 1; }
	docker compose --project-name awx -f awx/docker-compose.yml up -d
	echo -n "  Waiting for AWX API (may take ~2 min)..."
	for i in $$(seq 1 60); do
	    curl -sf --connect-timeout 3 http://localhost:8052/api/v2/ping/ -o /dev/null 2>/dev/null && { echo " ready"; break; }
	    [ $$i -eq 60 ] && { echo ""; echo -e "  $(CR)Timeout$(CX) — check: docker compose -p awx logs"; exit 1; }
	    sleep 5
	done

awx-down: ## Stop AWX
	@docker compose --project-name awx -f awx/docker-compose.yml down 2>/dev/null || true

awx-configure: ## Apply AWX-as-code (requires AWX_PASSWORD=<password>)
	@set -euo pipefail
	[ -n "$(AWX_PASSWORD)" ] || { echo -e "  $(CR)ERROR$(CX)  provide: make awx-configure AWX_PASSWORD=<pw>"; exit 1; }
	command -v ansible-playbook >/dev/null 2>&1 || { echo -e "  $(CR)ERROR$(CX)  ansible-playbook not found"; exit 1; }
	ansible-playbook awx/awx_config/configure_awx.yml \
	    -e "awx_host=$(AWX_HOST)" \
	    -e "awx_username=$(AWX_USER)" \
	    -e "awx_password=$(AWX_PASSWORD)"

##@ Services — AI Platform (local-aistack submodule)

# Must delegate to submodule Makefile — compose bind-mounts use ${PWD} which
# must resolve to local-aistack/, not the repo root.
aistack: ## Deploy local-aistack AI platform (Ollama, OpenWebUI, LiteLLM, MinIO, ...)
	@set -euo pipefail
	echo -e "$(CC)▶  AI Platform (local-aistack)$(CX)"
	[ -d local-aistack ] || { echo -e "  $(CR)ERROR$(CX)  local-aistack/ missing — run 'make submodules'"; exit 1; }
	[ -f local-aistack/env/.env.prod ] || { echo -e "  $(CR)ERROR$(CX)  local-aistack/env/.env.prod missing — run 'make envs'"; exit 1; }
	$(MAKE) -C local-aistack init
	$(MAKE) -C local-aistack up

aistack-down: ## Stop local-aistack AI platform
	@$(MAKE) -C local-aistack down 2>/dev/null || true

##@ Services — HomeCam (k3d cluster: sentinel-noc)

homecam: ## Deploy HomeCam NOC to k3d cluster sentinel-noc (creates ai-home-shared 172.30.0.0/24)
	@set -euo pipefail
	echo -e "$(CC)▶  HomeCam (k3d: sentinel-noc)$(CX)"
	[ -d HomeCam ] || { echo -e "  $(CR)ERROR$(CX)  HomeCam/ missing — run 'make submodules'"; exit 1; }
	$(MAKE) -C HomeCam k8s-up
	echo    "  Frontend NodePort : http://<host>:30080"
	echo    "  API NodePort      : http://<host>:30081"

homecam-down: ## Delete HomeCam k3d cluster sentinel-noc
	@k3d cluster delete sentinel-noc 2>/dev/null || true

##@ Services — Sentinel-Home (k3d cluster: sentinel-home)

sentinel-home: ## Deploy Sentinel-Home to k3d cluster sentinel-home (network: home-net)
	@set -euo pipefail
	echo -e "$(CC)▶  Sentinel-Home (k3d: sentinel-home)$(CX)"
	[ -d sentinel-home ] || { echo -e "  $(CR)ERROR$(CX)  sentinel-home/ missing — run 'make submodules'"; exit 1; }
	[ -f infra/sentinel-home/k3d-config.yaml ] || { echo -e "  $(CR)ERROR$(CX)  infra/sentinel-home/k3d-config.yaml not found"; exit 1; }
	if k3d cluster list 2>/dev/null | grep -q 'sentinel-home'; then
	    echo "  Cluster sentinel-home already exists — skipping create."
	else
	    k3d cluster create --config infra/sentinel-home/k3d-config.yaml
	fi
	manifest_dir="sentinel-home/deploy/kubernetes"
	if [ -d "$$manifest_dir" ] && ls "$$manifest_dir"/*.yaml >/dev/null 2>&1; then
	    kubectl --context k3d-sentinel-home apply -f "$$manifest_dir/"
	    echo "  Frontend NodePort : http://<host>:31000"
	    echo "  API NodePort      : http://<host>:31001"
	else
	    echo -e "  $(CY)WARN$(CX)  No manifests in $$manifest_dir — cluster created, deploy when ready."
	fi

sentinel-home-down: ## Delete Sentinel-Home k3d cluster
	@k3d cluster delete sentinel-home 2>/dev/null || true

##@ Observability

status: ## Show health status for all home-server services and k3d clusters
	@set -a; . "$(REPO)/.env" 2>/dev/null || true; set +a
	echo ""
	echo -e "$(CB)Service Status$(CX)"
	echo    "──────────────────────────────────────────────────────────"
	_chk() {
	    local name="$$1" url="$$2"
	    if curl -s --connect-timeout 3 "$$url" -o /dev/null 2>/dev/null; then
	        printf "  $(CG)UP  $(CX) %-22s  %s\n" "$$name" "$$url"
	    else
	        printf "  $(CR)DOWN$(CX) %-22s  %s\n" "$$name" "$$url"
	    fi
	}
	_chk "Traefik"   "http://localhost:80"
	_chk "Authentik" "http://localhost:9000/-/health/live/"
	_chk "AWX"       "http://localhost:8052/api/v2/ping/"
	echo ""
	echo -e "$(CB)Docker Compose stacks$(CX)"
	echo    "──────────────────────────────────────────────────────────"
	for proj in traefik-gw authentik awx ai-platform; do
	    running=$$(docker compose -p "$$proj" ps --services --filter status=running 2>/dev/null | wc -l | tr -d ' ')
	    total=$$(docker compose -p "$$proj" ps --services 2>/dev/null | wc -l | tr -d ' ')
	    if [ "$${total:-0}" -gt 0 ] 2>/dev/null; then
	        printf "  %-16s  %s/%s containers running\n" "$$proj" "$$running" "$$total"
	    else
	        printf "  $(CY)%-16s$(CX)  not deployed\n" "$$proj"
	    fi
	done
	echo ""
	echo -e "$(CB)k3d clusters$(CX)"
	echo    "──────────────────────────────────────────────────────────"
	k3d cluster list 2>/dev/null || echo "  k3d not available"
	echo ""
