---
- node:
    id: primary

- control-service:
    service: control
    filename: /var/run/receptor/receptor.sock

- work-command:
    worktype: local
    command: ansible-runner
    params: worker
    allowruntimeparams: true

- work-kubernetes:
    worktype: kubernetes
    authmethod: kubeconfig
    allowruntimeparams: true
