apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sentinel-noc
  labels:
    app: frontend
    app.kubernetes.io/part-of: sentinel-noc
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
