apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: sentinel-noc
  labels:
    app: mongodb
    app.kubernetes.io/part-of: sentinel-noc
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
