apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: sentinel-noc
  labels:
    app: backend
    app.kubernetes.io/part-of: sentinel-noc
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      nodePort: 30081
